---
sudo: required
dist: xenial
node_js:
  - "7"
before_install:
  - sudo apt-get install -y qtdeclarative5-dev-tools
before_script:
  - npm install -g eslint
language: generic
script:
  - find . -name \*.qml -exec /usr/lib/x86_64-linux-gnu/qt5/bin/qmllint {} \+
  - find . -name \*.js -exec eslint {} \+
  - find . -name \*.sh -exec shellcheck {} \+
